import Head from "next/head";
// import Image from "next/image";
// import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Navbar from "@/components/Navbar";
import Url from "@/components/Url";
import Twitter from "@/components/Twitter";
import Facebook from "@/components/Facebook";
export default function Home() {
  const [url, setUrl] = useState("");
  const [ogData, setOgData] = useState({});
  const [loading, setLoading] = useState(false);
  const handleUrlSubmission = async (url) => {
    setLoading(true);
    setUrl(url);
    const res = await fetch(`/api/scrape?url=${url}`);
    const data = await res.json();
    setOgData(data.result);
    setLoading(false);
  };
  return (
    <>
      <Head>
        <title>Metaspy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-white">
        <Navbar />
        <Url onUrlSubmit={handleUrlSubmission} loading={loading} />
        <div className="space-y-8">
          {ogData.ogTitle && ogData.ogImage && (
            <Twitter
              title={ogData.ogTitle}
              description={ogData.ogDescription}
              image={ogData.ogImage.url}
              url={ogData.requestUrl.replace(/https?:\/\//, "")}
            />
          )}
          {ogData.ogTitle && ogData.ogImage && (
            <Facebook
              title={ogData.ogTitle}
              description={ogData.ogDescription}
              image={ogData.ogImage.url}
              url={ogData.requestUrl.replace(/https?:\/\//, "")}
              fullUrl={ogData.requestUrl}
            />
          )}
        </div>
        {/* <section className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <code>
            <pre>{JSON.stringify(ogData, null, 2)}</pre>
          </code>
        </section> */}
      </main>
    </>
  );
}
